from policy import *
from people_generation import *
import os
import popularity
import simulation_callout
import policy_callout

indicator_dict = {
    'Immigrationdemand': round( simulation_callout.ImmigrationDemand,2),
    'Globalco2': round( simulation_callout.GlobalCO2,2),
    'Highincome': round( simulation_callout.HighIncome,2),
    'Lowincome': round( simulation_callout.LowIncome,2),
    'Middleincome': round( simulation_callout.middleincome,2),
    'Terrorism': round( simulation_callout.Terrorism,2),
    'Airtravel': round( simulation_callout.airtravel,2),
    'Alcoholconsumption': round( simulation_callout.alcoholconsumption,2),
    'Averagetemperature': round( simulation_callout.AverageTemperature,2),
    'Businessconfidence': round( simulation_callout.BusinessConfidence,2),
    'Bususage': round( simulation_callout.bususage,2),
    'Electriccartransition': round( simulation_callout.ElectricCarTransition,2),
    'Carusage': round( simulation_callout.carusage,2),
    'Charity': round( simulation_callout.charity,2),
    'Co2emissions': round( simulation_callout.co2emissions,2),
    'Corruption': round( simulation_callout.corruption,2),
    'Crimerate': round( simulation_callout.crimerate,2),
    'Racialtension': round( simulation_callout.RacialTension,2),
    'Democracy': round( simulation_callout.democracy,2),
    'Education': round( simulation_callout.education,2),
    'Emigration': round( simulation_callout.emigration,2),
    'Energyefficiency': round( simulation_callout.energyefficiency,2),
    'Environment': round( simulation_callout.environment,2),
    'Equality': round( simulation_callout.Equality,2),
    'Foodprice': round( simulation_callout.FoodPrice,2),
    'Currencystrength': round( simulation_callout.currencystrength,2),
    'Foreignaidreceived': round( simulation_callout.foreignaidreceived,2),
    'Foreigninvestment': round( simulation_callout.foreigninvestment,2),
    'Foreignrelations': round( simulation_callout.foreignrelations,2),
    'Gdp': round( simulation_callout.gdp,2),
    'Genderequality': round( simulation_callout.genderequality,2),
    'Generationalwealthgap': round( simulation_callout.generationalwealthgap,2),
    'Health': round( simulation_callout.health,2),
    'Tobaccouse': round( simulation_callout.tobaccouse,2),
    'Healthcaredemand': round( simulation_callout.healthcaredemand,2),
    'Humandevelopment': round( simulation_callout.humandevelopment,2),
    'Immigration': round( simulation_callout.immigration,2),
    'Illegalimmigration': round( simulation_callout.illegalimmigration,2),
    'Industrialautomation': round( simulation_callout.industrialautomation,2),
    'Inflation': round( simulation_callout.Inflation,2),
    'Internationaltrade': round( simulation_callout.internationaltrade,2),
    'Internetcurrencyadoption': round( simulation_callout.internetcurrencyadoption,2),
    'Internetspeed': round( simulation_callout.internetspeed,2),
    'Legaldrugconsumption': round( simulation_callout.legaldrugconsumption,2),
    'Lifespan': round( simulation_callout.lifespan,2),
    'Oildemand': round( simulation_callout.oildemand,2),
    'Oilprice': round( simulation_callout.oilprice,2),
    'Oilsupply': round( simulation_callout.oilsupply,2),
    'Population': round( simulation_callout.population,2),
    'Povertyrate': round( simulation_callout.povertyrate,2),
    'Privateenergy': round( simulation_callout.privateenergy,2),
    'Privatehealthcare': round( simulation_callout.privatehealthcare,2),
    'Privatehousing': round( simulation_callout.privatehousing,2),
    'Privatepensions': round( simulation_callout.privatepensions,2),
    'Privaterail': round( simulation_callout.privaterail,2),
    'Privateschools': round( simulation_callout.privateschools,2),
    'Privatetelecoms': round( simulation_callout.privatetelecoms,2),
    'Privatewater': round( simulation_callout.privatewater,2),
    'Railusage': round( simulation_callout.railUsage,2),
    'Stability': round( simulation_callout.stability,2),
    'Technology': round( simulation_callout.technology,2),
    'Tourism': round( simulation_callout.Tourism,2),
    'Trafficcongestion': round( simulation_callout.trafficcongestion,2),
    'Unemployment': round( simulation_callout.unemployment,2),
    'Veganism': round( simulation_callout.veganism,2),
    'Violentcrimerate': round( simulation_callout.violentcrimerate,2),
    'Wages': round( simulation_callout.wages,2),
    'Workerproductivity': round( simulation_callout.workerproductivity,2),
    'Workingweek': round( simulation_callout.workingweek,2),
    'Rareearthprice': round( simulation_callout.rareearthprice,2),
    'Mentalhealth': round( simulation_callout.mentalhealth,2),
    }

popularity_dict = {
    "Capitalism_popularity": round(popularity.Capitalism_popularity, 2),
    "Isolationism_popularity": round(popularity.Isolationism_popularity, 2),
    "Nationalism_popularity": round(popularity.Nationalism_popularity, 2),
    "Centrism_popularity": round(popularity.Centrism_popularity, 2),
    "Liberalism_popularity": round(popularity.Liberalism_popularity, 2),
    "Internationalism_popularity": round(popularity.Internationalism_popularity, 2),
    "Male_Supremacy_Advocates_popularity": round(popularity.Male_Supremacy_Advocates_popularity, 2),
    "Traditional_Law_and_Order_advocates_popularity": round(popularity.Traditional_Law_and_Order_advocates_popularity, 2),
    "Feminism_popularity": round(popularity.Feminism_popularity, 2),
    "Communism_popularity": round(popularity.Communism_popularity, 2),
    "Socialism_popularity": round(popularity.Socialism_popularity, 2),
    "Democratic_Socialism_popularity": round(popularity.Democratic_Socialism_popularity, 2),
    "Social_Democracy_popularity": round(popularity.Social_Democracy_popularity, 2),
    "Progressive_popularity": round(popularity.Progressive_popularity, 2),
    "Secularism_popularity": round(popularity.Secularism_popularity, 2),
    "Fiscal_Conservatism_popularity": round(popularity.Fiscal_Conservatism_popularity, 2),
    "Conservatism_popularity": round(popularity.Conservatism_popularity, 2),
    "Libertarian_Capitalism_popularity": round(popularity.Libertarian_Capitalism_popularity, 2),
    "Neoliberalism_popularity": round(popularity.Neoliberalism_popularity, 2),
    "Laissez_faire_Capitalism_popularity": round(popularity.Laissez_faire_Capitalism_popularity, 2),
    "Totalitarianism_popularity": round(popularity.Totalitarianism_popularity, 2),
    "Elitism_popularity": round(popularity.Elitism_popularity, 2),
    "Religious_Fundamentalism_popularity": round(popularity.Religious_Fundamentalism_popularity, 2),
    "Progressivism_popularity": round(popularity.Progressivism_popularity, 2),
    "Libertarianism_popularity": round(popularity.Libertarianism_popularity, 2),
    "Anarchism_popularity": round(popularity.Anarchism_popularity, 2),
    "Environmentalism_popularity": round(popularity.Environmentalism_popularity, 2),
    "Technological_Optimism_popularity": round(popularity.Technological_Optimism_popularity, 2),
    "Industrialism_popularity": round(popularity.Industrialism_popularity, 2),
    "Altruism_popularity": round(popularity.Altruism_popularity, 2),
    "Collectivism_popularity": round(popularity.Collectivism_popularity, 2),
    "Individualism_popularity": round(popularity.Individualism_popularity, 2),
    "Egoism_popularity": round(popularity.Egoism_popularity, 2),
    "Populism_popularity": round(popularity.Populism_popularity, 2),
    "Free_Trade_Advocates_popularity": round(popularity.Free_Trade_Advocates_popularity, 2),
    "Protectionism_popularity": round(popularity.Protectionism_popularity, 2),
    "Economic_Nationalism_popularity": round(popularity.Economic_Nationalism_popularity, 2),
    "Postmodernism_popularity": round(popularity.Postmodernism_popularity, 2),
    "Modernism_popularity": round(popularity.Modernism_popularity, 2),
    "Scientific_Progressivism_popularity": round(popularity.Scientific_Progressivism_popularity, 2),
    "Cultural_Traditionalism_popularity": round(popularity.Cultural_Traditionalism_popularity, 2),
    "Traditionalism_popularity": round(popularity.Traditionalism_popularity, 2),
    "Globalization_supporters_popularity": round(popularity.Globalization_supporters_popularity, 2),
    "International_Cooperation_Advocates_popularity": round(popularity.International_Cooperation_Advocates_popularity, 2),
    "Patriotic_movements_popularity": round(popularity.Patriotic_movements_popularity, 2),
    "National_Security_Advocates_popularity": round(popularity.National_Security_Advocates_popularity, 2),
    "Patriotic_Education_Advocates_popularity": round(popularity.Patriotic_Education_Advocates_popularity, 2),
    "AntiCorruption_movements_popularity": round(popularity.AntiCorruption_movements_popularity, 2),
    "Labor_Movements_popularity": round(popularity.Labor_Movements_popularity, 2),
    "Social_Welfare_Advocates_popularity": round(popularity.Social_Welfare_Advocates_popularity, 2),
    "Educational_Equity_Advocates_popularity": round(popularity.Educational_Equity_Advocates_popularity, 2),
    "Universal_Healthcare_Advocates_popularity": round(popularity.Universal_Healthcare_Advocates_popularity, 2),
    "Market_Reform_Advocates_popularity": round(popularity.Market_Reform_Advocates_popularity, 2),
    "Tax_Reform_advocates_popularity": round(popularity.Tax_Reform_advocates_popularity, 2),
    "Redistribution_Advocates_popularity": round(popularity.Redistribution_Advocates_popularity, 2),
    "Economic_Equality_Advocates_popularity": round(popularity.Economic_Equality_Advocates_popularity, 2),
    "Housing_Equity_Advocates_popularity": round(popularity.Housing_Equity_Advocates_popularity, 2),
    "Economic_Stimulus_Advocates_popularity": round(popularity.Economic_Stimulus_Advocates_popularity, 2),
    "Global_Climate_Change_Advocates_popularity": round(popularity.Global_Climate_Change_Advocates_popularity, 2),
    "Animal_Rights_Advocates_popularity": round(popularity.Animal_Rights_Advocates_popularity, 2),
    "Climate_Change_Advocates_popularity": round(popularity.Climate_Change_Advocates_popularity, 2),
    "Sustainable_Agriculture_Advocates_popularity": round(popularity.Sustainable_Agriculture_Advocates_popularity, 2),
    "Human_Rights_movements_popularity": round(popularity.Human_Rights_movements_popularity, 2),
    "Democracy_advocates_popularity": round(popularity.Democracy_advocates_popularity, 2),
    "Civil_Liberties_Advocates_popularity": round(popularity.Civil_Liberties_Advocates_popularity, 2),
    "Social_Justice_Advocates_popularity": round(popularity.Social_Justice_Advocates_popularity, 2),
    "Social_Equality_Advocates_popularity": round(popularity.Social_Equality_Advocates_popularity, 2),
    "Individual_Rights_Advocates_popularity": round(popularity.Individual_Rights_Advocates_popularity, 2),
    "Privacy_advocates_popularity": round(popularity.Privacy_advocates_popularity, 2),
    "Open_Source_Advocates_popularity": round(popularity.Open_Source_Advocates_popularity, 2),
    "Cryptocurrency_Advocates_popularity": round(popularity.Cryptocurrency_Advocates_popularity, 2),
    "Digital_Freedom_Advocates_popularity": round(popularity.Digital_Freedom_Advocates_popularity, 2),
    "Digital_Economy_Advocates_popularity": round(popularity.Digital_Economy_Advocates_popularity, 2),
    "Free_Internet_Advocates_popularity": round(popularity.Free_Internet_Advocates_popularity, 2),
    "Community_movements_popularity": round(popularity.Community_movements_popularity, 2),
    "Peace_movements_popularity": round(popularity.Peace_movements_popularity, 2),
    "Consumer_Rights_advocates_popularity": round(popularity.Consumer_Rights_advocates_popularity, 2),
    "Science_education_advocates_popularity": round(popularity.Science_education_advocates_popularity, 2),
    "Free_Market_Advocates_popularity": round(popularity.Free_Market_Advocates_popularity, 2),
    "Regulation_Advocates_popularity": round(popularity.Regulation_Advocates_popularity, 2),
    "Gun_Rights_Advocates_popularity": round(popularity.Gun_Rights_Advocates_popularity, 2),
    "Drug_Reform_Advocates_popularity": round(popularity.Drug_Reform_Advocates_popularity, 2),
    "Law_and_Order_Advocates_popularity": round(popularity.Law_and_Order_Advocates_popularity, 2),
    "Anti_Militarism_Advocates_popularity": round(popularity.Anti_Militarism_Advocates_popularity, 2),
    "Harm_Reduction_Advocates_popularity": round(popularity.Harm_Reduction_Advocates_popularity, 2),
    "Hardline_Drug_Policy_Advocates_popularity": round(popularity.Hardline_Drug_Policy_Advocates_popularity, 2),
    "Anti_Nuclear_Advocates_popularity": round(popularity.Anti_Nuclear_Advocates_popularity, 2),
    "Medical_Ethics_Advocates_popularity": round(popularity.Medical_Ethics_Advocates_popularity, 2),
    "Health_movements_popularity": round(popularity.Health_movements_popularity, 2),
    "Housing_rights_activists_popularity": round(popularity.Housing_rights_activists_popularity, 2),
    "Public_Transport_Advocates_popularity": round(popularity.Public_Transport_Advocates_popularity, 2),
    "Homeownership_Advocates_popularity": round(popularity.Homeownership_Advocates_popularity, 2),
    "Religious_popularity": round(popularity.Religious_popularity, 2),
    "Young_popularity": round(popularity.Young_popularity, 2),
    "Patriot_popularity": round(popularity.Patriot_popularity, 2),
    "Parents_popularity": round(popularity.Parents_popularity, 2),
    "Middle_Class_popularity": round(popularity.Middle_Class_popularity, 2),
    "Poor_popularity": round(popularity.Poor_popularity, 2),
    "Wealthy_popularity": round(popularity.Wealthy_popularity, 2),
    "Commuter_popularity": round(popularity.Commuter_popularity, 2),
    "Motorist_popularity": round(popularity.Motorist_popularity, 2),
    "Academic_popularity": round(popularity.Academic_popularity, 2),
    "Blue_Collar_Worker_popularity": round(popularity.Blue_Collar_Worker_popularity, 2),
    "Farmers_popularity": round(popularity.Farmers_popularity, 2),
    "Grey_Collar_Worker_popularity": round(popularity.Grey_Collar_Worker_popularity, 2),
    "Retired_popularity": round(popularity.Retired_popularity, 2),
    "Self_Employed_popularity": round(popularity.Self_Employed_popularity, 2),
    "State_Employees_popularity": round(popularity.State_Employees_popularity, 2),
    "Student_popularity": round(popularity.Student_popularity, 2),
    "Unemployed_popularity": round(popularity.Unemployed_popularity, 2),
    "White_Collar_Worker_popularity": round(popularity.White_Collar_Worker_popularity, 2)
}

policy_dict = {
    "abortionlaw":policy_callout.Abortionlaw, 
    "adulteducationsubsidies":policy_callout.Adulteducationsubsidies, 
    "agriculturesubsidies":policy_callout.Agriculturesubsidies, 
    "airlinetax":policy_callout.Airlinetax, 
    "alcoholawarenesscampaign":policy_callout.Alcoholawarenesscampaign, 
    "alcohollaw":policy_callout.Alcohollaw, 
    "alcoholtax":policy_callout.Alcoholtax, 
    "antibioticsban":policy_callout.Antibioticsban, 
    "anticorruptionagency":policy_callout.Anticorruptionagency, 
    "armedpolice":policy_callout.Armedpolice, 
    "artssubsidies":policy_callout.Artssubsidies, 
    "automationtax":policy_callout.Automationtax, 
    "bancoal":policy_callout.Bancoal, 
    "bandivorce":policy_callout.Bandivorce, 
    "banforeignchurchservice":policy_callout.Banforeignchurchservice, 
    "banhomosexuality":policy_callout.Banhomosexuality, 
    "banlowmpgcars":policy_callout.Banlowmpgcars, 
    "banprivateeducation":policy_callout.Banprivateeducation, 
    "banprivatehealthcare":policy_callout.Banprivatehealthcare, 
    "bansecondhomeownership":policy_callout.Bansecondhomeownership, 
    "bansundayshopping":policy_callout.Bansundayshopping, 
    "bicyclesubsidies":policy_callout.Bicyclesubsidies, 
    "biofuelsubsidies":policy_callout.Biofuelsubsidies, 
    "bodycameras":policy_callout.Bodycameras, 
    "bordercontrols":policy_callout.Bordercontrols, 
    "borderwall":policy_callout.Borderwall, 
    "businessstartupcampaign":policy_callout.Businessstartupcampaign, 
    "buslanes":policy_callout.Buslanes, 
    "bussubsidies":policy_callout.Bussubsidies, 
    "capceopaymultiplier":policy_callout.Capceopaymultiplier, 
    "capitalcontrols":policy_callout.Capitalcontrols, 
    "capitalgainstax":policy_callout.Capitalgainstax, 
    "carboncaptureandstorage":policy_callout.Carboncaptureandstorage, 
    "carbontax":policy_callout.Carbontax, 
    "caremmissionslimits":policy_callout.Caremmissionslimits, 
    "carpoolingcampaign":policy_callout.Carpoolingcampaign, 
    "cartax":policy_callout.Cartax, 
    "cctvcameras":policy_callout.Cctvcameras, 
    "charitytaxrelief":policy_callout.Charitytaxrelief, 
    "childbenefit":policy_callout.Childbenefit, 
    "childcareprovision":policy_callout.Childcareprovision, 
    "citizenshiptests":policy_callout.Citizenshiptests, 
    "cityfarms":policy_callout.Cityfarms, 
    "cleanenergysubsidies":policy_callout.Cleanenergysubsidies, 
    "cleanfuelsubsidy":policy_callout.Cleanfuelsubsidy, 
    "climatechangeadaptionfund":policy_callout.Climatechangeadaptionfund, 
    "closeairportscompletely":policy_callout.Closeairportscompletely, 
    "communitypolicing":policy_callout.Communitypolicing, 
    "compulsorychurchattendance":policy_callout.Compulsorychurchattendance, 
    "compulsoryfoodlabelling":policy_callout.Compulsoryfoodlabelling, 
    "compulsoryforeignlanguageclasses":policy_callout.Compulsoryforeignlanguageclasses, 
    "compulsorylanguagelessons":policy_callout.Compulsorylanguagelessons, 
    "compulsoryschoolsports":policy_callout.Compulsoryschoolsports, 
    "compulsoryworkfortheunemployed":policy_callout.Compulsoryworkfortheunemployed, 
    "congestioncharging":policy_callout.Congestioncharging, 
    "consumerrights":policy_callout.Consumerrights, 
    "corporationtax":policy_callout.Corporationtax, 
    "creationism":policy_callout.Creationism, 
    "curfews":policy_callout.Curfews, 
    "cyberbullyingawarenesscampaign":policy_callout.Cyberbullyingawarenesscampaign, 
    "cyclingcampaign":policy_callout.Cyclingcampaign, 
    "deathpenalty":policy_callout.Deathpenalty, 
    "detentionwithouttrial":policy_callout.Detentionwithouttrial, 
    "diplomaticservice":policy_callout.Diplomaticservice, 
    "disabilitybenefit":policy_callout.Disabilitybenefit, 
    "diversityquotasforcompanies":policy_callout.Diversityquotasforcompanies, 
    "divertedprofitstax":policy_callout.Divertedprofitstax, 
    "driverlesscarlaws":policy_callout.Driverlesscarlaws, 
    "dronestrikeact":policy_callout.Dronestrikeact, 
    "drugenforcement":policy_callout.Drugenforcement, 
    "drugtreatment":policy_callout.Drugtreatment, 
    "ecohomeregulations":policy_callout.Ecohomeregulations, 
    "electriccarsinitiative":policy_callout.Electriccarsinitiative, 
    "emptyhomestax":policy_callout.Emptyhomestax, 
    "enterpriseinvestmentscheme":policy_callout.Enterpriseinvestmentscheme, 
    "executivetermlength":policy_callout.Executivetermlength, 
    "executivetermlimit":policy_callout.Executivetermlimit, 
    "faithschoolsubsidies":policy_callout.Faithschoolsubsidies, 
    "familyplanning":policy_callout.Familyplanning, 
    "femalegenitalmutilationban":policy_callout.Femalegenitalmutilationban, 
    "financialtransactionstax":policy_callout.Financialtransactionstax, 
    "flagsoneverystreetcorner":policy_callout.Flagsoneverystreetcorner, 
    "flattax":policy_callout.Flattax, 
    "foodstamps":policy_callout.Foodstamps, 
    "foodstandards":policy_callout.Foodstandards, 
    "foreignaid":policy_callout.Foreignaid, 
    "foreigninvestmentrestrictions":policy_callout.Foreigninvestmentrestrictions, 
    "foreigninvestortaxbreaks":policy_callout.Foreigninvestortaxbreaks, 
    "freebuspasses":policy_callout.Freebuspasses, 
    "freeeyetests":policy_callout.Freeeyetests, 
    "freeparentingclasses":policy_callout.Freeparentingclasses, 
    "freeschoolmeals":policy_callout.Freeschoolmeals, 
    "frequentflyertax":policy_callout.Frequentflyertax, 
    "fuelefficiency":policy_callout.Fuelefficiency, 
    "gambling":policy_callout.Gambling, 
    "gamehunting":policy_callout.Gamehunting, 
    "gatedcommunities":policy_callout.Gatedcommunities, 
    "gaymarriage":policy_callout.Gaymarriage, 
    "genderdiscriminationact":policy_callout.Genderdiscriminationact, 
    "gendertransition":policy_callout.Gendertransition, 
    "generalmediacensorship":policy_callout.Generalmediacensorship, 
    "governmentsubsidiesforunions":policy_callout.Governmentsubsidiesforunions, 
    "graduatetax":policy_callout.Graduatetax, 
    "greenelectronicsinitiative":policy_callout.Greenelectronicsinitiative, 
    "handgunlaws":policy_callout.Handgunlaws, 
    "healthcarevouchers":policy_callout.Healthcarevouchers, 
    "healthfoodsubsidies":policy_callout.Healthfoodsubsidies, 
    "healthtaxcredits":policy_callout.Healthtaxcredits, 
    "healthyeatingcampaign":policy_callout.Healthyeatingcampaign, 
    "helicoptermoney":policy_callout.Helicoptermoney, 
    "humancloningresearchgrants":policy_callout.Humancloningresearchgrants, 
    "hybridcarsinitiative":policy_callout.Hybridcarsinitiative, 
    "idcards":policy_callout.Idcards, 
    "importtarrifs":policy_callout.Importtarrifs, 
    "incometax":policy_callout.Incometax, 
    "inheritancetax":policy_callout.Inheritancetax, 
    "intellectualpropertyrights":policy_callout.Intellectualpropertyrights, 
    "intelligenceservices":policy_callout.Intelligenceservices, 
    "internationalfusionresearchproject":policy_callout.Internationalfusionresearchproject, 
    "internetcensorship":policy_callout.Internetcensorship, 
    "internetcurrencytaxation":policy_callout.Internetcurrencytaxation, 
    "internettax":policy_callout.Internettax, 
    "judiciaryindependence":policy_callout.Judiciaryindependence, 
    "junkfoodtax":policy_callout.Junkfoodtax, 
    "jurytrial":policy_callout.Jurytrial, 
    "keepthecountrytidycampaign":policy_callout.Keepthecountrytidycampaign, 
    "labordaybankholiday":policy_callout.Labordaybankholiday, 
    "labourlaws":policy_callout.Labourlaws, 
    "legalaid":policy_callout.Legalaid, 
    "legaliseprostitution":policy_callout.Legaliseprostitution, 
    "limitautomatedtrading":policy_callout.Limitautomatedtrading, 
    "limitorbancarsincities":policy_callout.Limitorbancarsincities, 
    "luxurygoodstax":policy_callout.Luxurygoodstax, 
    "mandatorymicrochipimplant":policy_callout.Mandatorymicrochipimplant, 
    "mandatorymicrogeneration":policy_callout.Mandatorymicrogeneration, 
    "mansiontax":policy_callout.Mansiontax, 
    "marriedtaxallowance":policy_callout.Marriedtaxallowance, 
    "marsprogram":policy_callout.Marsprogram, 
    "maternityleave":policy_callout.Maternityleave, 
    "microgenerationgrants":policy_callout.Microgenerationgrants, 
    "militaryspending":policy_callout.Militaryspending, 
    "minimumwage":policy_callout.Minimumwage, 
    "monorail":policy_callout.Monorail, 
    "mortgagetaxrelief":policy_callout.Mortgagetaxrelief, 
    "narcotics":policy_callout.Narcotics, 
    "nationalanthematstartofnews":policy_callout.Nationalanthematstartofnews, 
    "nationalanthemsinschool":policy_callout.Nationalanthemsinschool, 
    "nationalarmedforcesweek":policy_callout.Nationalarmedforcesweek, 
    "nationalbusinesscouncil":policy_callout.Nationalbusinesscouncil, 
    "nationalservice":policy_callout.Nationalservice, 
    "needleexchangeprogram":policy_callout.Needleexchangeprogram, 
    "newcarsubsidies":policy_callout.Newcarsubsidies, 
    "nuclearfission":policy_callout.Nuclearfission, 
    "oildrillingsubsidy":policy_callout.Oildrillingsubsidy, 
    "onechildpolicy":policy_callout.Onechildpolicy, 
    "organdonation":policy_callout.Organdonation, 
    "organicsubsidy":policy_callout.Organicsubsidy, 
    "payrolltax":policy_callout.Payrolltax, 
    "petroltax":policy_callout.Petroltax, 
    "phonetapping":policy_callout.Phonetapping, 
    "plasticbagtax":policy_callout.Plasticbagtax, 
    "policedrones":policy_callout.Policedrones, 
    "pollutioncontrols":policy_callout.Pollutioncontrols, 
    "pressfreedom":policy_callout.Pressfreedom, 
    "prisonertagging":policy_callout.Prisonertagging, 
    "prisonervoting":policy_callout.Prisonervoting, 
    "privateprisons":policy_callout.Privateprisons, 
    "propertytax":policy_callout.Propertytax, 
    "proportionalfines":policy_callout.Proportionalfines, 
    "publiclibraries":policy_callout.Publiclibraries, 
    "publicreligiousbroadcasts":policy_callout.Publicreligiousbroadcasts, 
    "publictaxreturns":policy_callout.Publictaxreturns, 
    "punitivetaxonsuperstores":policy_callout.Punitivetaxonsuperstores, 
    "punitivewealthtax":policy_callout.Punitivewealthtax, 
    "quantitativeeasing":policy_callout.Quantitativeeasing, 
    "racediscriminationact":policy_callout.Racediscriminationact, 
    "racialprofiling":policy_callout.Racialprofiling, 
    "rareearthrefinement":policy_callout.Rareearthrefinement, 
    "recreationaldrugstax":policy_callout.Recreationaldrugstax, 
    "recycling":policy_callout.Recycling, 
    "reforestation":policy_callout.Reforestation, 
    "rentcontrols":policy_callout.Rentcontrols, 
    "retirementage":policy_callout.Retirementage, 
    "righttodie":policy_callout.Righttodie, 
    "righttoprivacy":policy_callout.Righttoprivacy, 
    "roadbuilding":policy_callout.Roadbuilding, 
    "roboticsresearch":policy_callout.Roboticsresearch, 
    "rubberbullets":policy_callout.Rubberbullets, 
    "ruraldevelopmentgrants":policy_callout.Ruraldevelopmentgrants, 
    "salestax":policy_callout.Salestax, 
    "sateliteroadpricing":policy_callout.Sateliteroadpricing, 
    "schoolbuses":policy_callout.Schoolbuses, 
    "schoolprayers":policy_callout.Schoolprayers, 
    "schooltaxcredits":policy_callout.Schooltaxcredits, 
    "schoolvouchers":policy_callout.Schoolvouchers, 
    "sciencefunding":policy_callout.Sciencefunding, 
    "secretcourts":policy_callout.Secretcourts, 
    "selectiveschooling":policy_callout.Selectiveschooling, 
    "smallbusinessgrants":policy_callout.Smallbusinessgrants, 
    "smartmeterprogram":policy_callout.Smartmeterprogram, 
    "socialcare":policy_callout.Socialcare, 
    "socialjusticefoundation":policy_callout.Socialjusticefoundation, 
    "spaceprogram":policy_callout.Spaceprogram, 
    "statebroadcaster":policy_callout.Statebroadcaster, 
    "statehealthservice":policy_callout.Statehealthservice, 
    "stateschools":policy_callout.Stateschools, 
    "stemcells":policy_callout.Stemcells, 
    "syntheticmeatresearchgrants":policy_callout.Syntheticmeatresearchgrants, 
    "universalbasicincome":policy_callout.Universalbasicincome, 
    "refugeepolicy":policy_callout.Refugeepolicy, 
    "statereligion":policy_callout.Statereligion, 
    "desalination":policy_callout.Desalination, 
    "immigrationrules":policy_callout.Immigrationrules, 
    "nuclearweapons":policy_callout.Nuclearweapons, 
    "co2campaign":policy_callout.Co2campaign, 
    "banalcohol":policy_callout.Banalcohol, 
    "bantobacco":policy_callout.Bantobacco, 
    "bancrypto":policy_callout.Bancrypto, 
    "workersdividend":policy_callout.Workersdividend
}

