from policy import *
import simulation_callout
from policy_callout_dict import update_random, policy_callout_dict as pcd
import json


policy_callout_dict = {
    'Abortionlaw': [],
    'Agriculturesubsidies': [],
    'Airlinetax': [],
    'Alcoholtax': [],
    'Artssubsidies': [],
    'Bantobacco': [],
    'Bodycameras': [],
    'Bordercontrols': [],
    'Buslanes': [],
    'Bussubsidies': [],
    'Cctvcameras': [],
    'Capitalgainstax': [],
    'Caremmissionslimits': [],
    'Cartax': [],
    'Charitytaxrelief': [],
    'Childbenefit': [],
    'Citizenshiptests': [],
    'Cleanenergysubsidies': [],
    'Communitypolicing': [],
    'Compulsoryfoodlabelling': [],
    'Compulsoryschoolsports': [],
    'Consumerrights': [],
    'Corporationtax': [],
    'Creationism': [],
    'Disabilitybenefit': [],
    'Divertedprofitstax': [],
    'Executivetermlimit': [],
    'Executivetermlength': [],
    'Familyplanning': [],
    'Femalegenitalmutilationban': [],
    'Foodstandards': [],
    'Foreignaid': [],
    'Foreigninvestortaxbreaks': [],
    'Freebuspasses': [],
    'Freeschoolmeals': [],
    'Gambling': [],
    'Gamehunting': [],
    'Gaymarriage': [],
    'Genderdiscriminationact': [],
    'Gendertransition': [],
    'Graduatetax': [],
    'Handgunlaws': [],
    'Hybridcarsinitiative': [],
    'Incometax': [],
    'Inheritancetax': [],
    'Intellectualpropertyrights': [],
    'Judiciaryindependence': [],
    'Junkfoodtax': [],
    'Jurytrial': [],
    'Labordaybankholiday': [],
    'Labourlaws': [],
    'Legalaid': [],
    'Maternityleave': [],
    'Militaryspending': [],
    'Minimumwage': [],
    'Narcotics': [],
    'Nuclearfission': [],
    'Nuclearweapons': [],
    'Organdonation': [],
    'Payrolltax': [],
    'Petroltax': [],
    'Plasticbagtax': [],
    'Pollutioncontrols': [],
    'Pressfreedom': [],
    'Prisonertagging': [],
    'Propertytax': [],
    'Publiclibraries': [],
    'Racediscriminationact': [],
    'Recycling': [],
    'Retirementage': [],
    'Roadbuilding': [],
    'Salestax': [],
    'Sciencefunding': [],
    'Selectiveschooling': [],
    'Smartmeterprogram': [],
    'Socialcare': [],
    'Statebroadcaster': [],
    'Statehealthservice': [],
    'Stateschools': [],
    'Stemcells': [],
    'Adulteducationsubsidies': [],
    'Alcoholawarenesscampaign': [],
    'Alcohollaw': [],
    'Alcoholawarenesscampaign': [],
    'Antibioticsban': [],
    'Anticorruptionagency': [],
    'Armedpolice': [],
    'Automationtax': [],
    'Bancoal': [],
    'Bandivorce': [],
    'Banforeignchurchservice': [],
    'Banhomosexuality': [],
    'Banlowmpgcars': [],
    'Banprivateeducation': [],
    'Banprivatehealthcare': [],
    'Bansecondhomeownership': [],
    'Bansundayshopping': [],
    'Bicyclesubsidies': [],
    'Biofuelsubsidies': [],
    'Borderwall': [],
    'Businessstartupcampaign': [],
    'Capceopaymultiplier': [],
    'Capitalcontrols': [],
    'Carboncaptureandstorage': [],
    'Carbontax': [],
    'Carpoolingcampaign': [],
    'Childcareprovision': [],
    'Cityfarms': [],
    'Cleanfuelsubsidy': [],
    'Climatechangeadaptionfund': [],
    'Closeairportscompletely': [],
    'Compulsorychurchattendance': [],
    'Compulsoryforeignlanguageclasses': [],
    'Compulsorylanguagelessons': [],
    'Compulsoryworkfortheunemployed': [],
    'Congestioncharging': [],
    'Curfews': [],
    'Cyberbullyingawarenesscampaign': [],
    'Cyclingcampaign': [],
    'Deathpenalty': [],
    'Detentionwithouttrial': [],
    'Diplomaticservice': [],
    'Diversityquotasforcompanies': [],
    'Driverlesscarlaws': [],
    'Dronestrikeact': [],
    'Drugenforcement': [],
    'Drugtreatment': [],
    'Ecohomeregulations': [],
    'Electriccarsinitiative': [],
    'Emptyhomestax': [],
    'Enterpriseinvestmentscheme': [],
    'Faithschoolsubsidies': [],
    'Financialtransactionstax': [],
    'Flagsoneverystreetcorner': [],
    'Flattax': [],
    'Foodstamps': [],
    'Foreigninvestmentrestrictions': [],
    'Freeeyetests': [],
    'Freeparentingclasses': [],
    'Frequentflyertax': [],
    'Fuelefficiency': [],
    'Gatedcommunities': [],
    'Generalmediacensorship': [],
    'Governmentsubsidiesforunions': [],
    'Greenelectronicsinitiative': [],
    'Healthcarevouchers': [],
    'Healthfoodsubsidies': [],
    'Healthtaxcredits': [],
    'Healthyeatingcampaign': [],
    'Helicoptermoney': [],
    'Humancloningresearchgrants': [],
    'Idcards': [],
    'Importtarrifs': [],
    'Intelligenceservices': [],
    'Internationalfusionresearchproject': [],
    'Internetcensorship': [],
    'Internetcurrencytaxation': [],
    'Internettax': [],
    'Keepthecountrytidycampaign': [],
    'Legaliseprostitution': [],
    'Limitautomatedtrading': [],
    'Limitorbancarsincities': [],
    'Luxurygoodstax': [],
    'Mandatorymicrochipimplant': [],
    'Mandatorymicrogeneration': [],
    'Mansiontax': [],
    'Marriedtaxallowance': [],
    'Marsprogram': [],
    'Microgenerationgrants': [],
    'Monorail': [],
    'Mortgagetaxrelief': [],
    'Nationalanthematstartofnews': [],
    'Nationalanthemsinschool': [],
    'Nationalarmedforcesweek': [],
    'Nationalbusinesscouncil': [],
    'Nationalservice': [],
    'Needleexchangeprogram': [],
    'Newcarsubsidies': [],
    'Oildrillingsubsidy': [],
    'Onechildpolicy': [],
    'Organicsubsidy': [],
    'Phonetapping': [],
    'Policedrones': [],
    'Prisonervoting': [],
    'Privateprisons': [],
    'Proportionalfines': [],
    'Publicreligiousbroadcasts': [],
    'Publictaxreturns': [],
    'Punitivetaxonsuperstores': [],
    'Punitivewealthtax': [],
    'Quantitativeeasing': [],
    'Racialprofiling': [],
    'Rareearthrefinement': [],
    'Recreationaldrugstax': [],
    'Reforestation': [],
    'Rentcontrols': [],
    'Righttodie': [],
    'Righttoprivacy': [],
    'Roboticsresearch': [],
    'Rubberbullets': [],
    'Ruraldevelopmentgrants': [],
    'Sateliteroadpricing': [],
    'Schoolbuses': [],
    'Schoolprayers': [],
    'Schooltaxcredits': [],
    'Schoolvouchers': [],
    'Secretcourts': [],
    'Smallbusinessgrants': [],
    'Socialjusticefoundation': [],
}

popularity_dict_list = {
    "Capitalism_popularity":[],
    'Isolationism_popularity' : [],
    'Nationalism_popularity' : [],
    'Centrism_popularity' : [],
    'Liberalism_popularity' : [],
    'Internationalism_popularity' : [],
    'Male_Supremacy_Advocates_popularity' : [],
    'Traditional_Law_and_Order_advocates_popularity' : [],
    'Centrism_popularity' : [],
    'Feminism_popularity' : [],
    'Communism_popularity' : [],
    'Socialism_popularity' : [],
    'Democratic_Socialism_popularity' : [],
    'Social_Democracy_popularity' : [],
    'Progressive_popularity' : [],
    'Liberalism_popularity' : [],
    'Secularism_popularity' : [],
    'Fiscal_Conservatism_popularity' : [],
    'Conservatism_popularity' : [],
    'Libertarian_Capitalism_popularity' : [],
    'Neoliberalism_popularity' : [],
    'Laissez_faire_Capitalism_popularity' : [],
    'Totalitarianism_popularity' : [],
    'Elitism_popularity' : [],
    'Religious_Fundamentalism_popularity' : [],
    'Nationalism_popularity' : [],
    'Liberalism_popularity' : [],
    'Progressivism_popularity' : [],
    'Libertarianism_popularity' : [],
    'Anarchism_popularity' : [],
    'Environmentalism_popularity' : [],
    'Technological_Optimism_popularity' : [],
    'Industrialism_popularity' : [],
    'Altruism_popularity' : [],
    'Collectivism_popularity' : [],
    'Centrism_popularity' : [],
    'Individualism_popularity' : [],
    'Egoism_popularity' : [],
    'Populism_popularity' : [],
    'Free_Trade_Advocates_popularity' : [],
    'Protectionism_popularity' : [],
    'Economic_Nationalism_popularity' : [],
    'Postmodernism_popularity' : [],
    'Modernism_popularity' : [],
    'Scientific_Progressivism_popularity' : [],
    'Cultural_Traditionalism_popularity' : [],
    'Traditionalism_popularity' : [],
    'EthnicMinorities_popularity' : [],
    'Cultural_Relativism_popularity' : [],
    'Globalization_supporters_popularity' : [],
    'International_Cooperation_Advocates_popularity' : [],
    'Patriotic_movements_popularity' : [],
    'National_Security_Advocates_popularity' : [],
    'Patriotic_Education_Advocates_popularity' : [],
    'AntiCorruption_movements_popularity' : [],
    'Labor_Movements_popularity' : [],
    'Social_Welfare_Advocates_popularity' : [],
    'Educational_Equity_Advocates_popularity' : [],
    'Universal_Healthcare_Advocates_popularity' : [],
    'Market_Reform_Advocates_popularity' : [],
    'Tax_Reform_advocates_popularity' : [],
    'Redistribution_Advocates_popularity' : [],
    'Economic_Equality_Advocates_popularity' : [],
    'Housing_Equity_Advocates_popularity' : [],
    'Economic_Stimulus_Advocates_popularity' : [],
    'Global_Climate_Advocates_popularity' : [],
    'Animal_Rights_Advocates_popularity' : [],
    'Climate_Advocates_popularity' : [],
    'Sustainable_Agriculture_Advocates_popularity' : [],
    'Human_Rights_movements_popularity' : [],
    'Democracy_advocates_popularity' : [],
    'Civil_Liberties_Advocates_popularity' : [],
    'Social_Justice_Advocates_popularity' : [],
    'Social_Equality_Advocates_popularity' : [],
    'Individual_Rights_Advocates_popularity' : [],
    'Privacy_advocates_popularity' : [],
    'Open_Source_Advocates_popularity' : [],
    'Cryptocurrency_Advocates_popularity' : [],
    'Digital_Freedom_Advocates_popularity' : [],
    'Digital_Economy_Advocates_popularity' : [],
    'Free_Internet_Advocates_popularity' : [],
    'Community_movements_popularity' : [],
    'Peace_movements_popularity' : [],
    'Consumer_Rights_advocates_popularity' : [],
    'Science_education_advocates_popularity' : [],
    'Free_Market_Advocates_popularity' : [],
    'Free_Trade_Advocates_popularity' : [],
    'Regulation_Advocates_popularity' : [],
    'Gun_Rights_Advocates_popularity' : [],
    'Drug_Reform_Advocates_popularity' : [],
    'Law_and_Order_Advocates_popularity' : [],
    'Anti_Militarism_Advocates_popularity' : [],
    'Harm_Reduction_Advocates_popularity' : [],
    'Hardline_Drug_Policy_Advocates_popularity' : [],
    'Anti_Nuclear_Advocates_popularity' : [],
    'Medical_Ethics_Advocates_popularity' : [],
    'Health_movements_popularity' : [],
    'Housing_rights_activists_popularity' : [],
    'Public_Transport_Advocates_popularity' : [],
    'Homeownership_Advocates_popularity' : [],
    'Privacy_Advocates_popularity' : [],
    'Human_Rights_Advocacy_popularity' : [],
    'Wealth_Preservation_Advocates_popularity' : [],
    'Urban_Development_Advocates_popularity' : [],
    'Free_Speech_Advocates_popularity' : [],
    'Religious_popularity' : [],
    'Young_popularity' : [],
    'Patriot_popularity' : [],
    'Parents_popularity' : [],
    'Middle_Class_popularity' : [],
    'Poor_popularity' : [],
    'Wealthy_popularity' : [],
    'Commuter_popularity' : [],
    'Motorist_popularity' : [],
    'Academic_popularity' : [],
    'Blue_Collar_Worker_popularity' : [],
    'Farmers_popularity' : [],
    'Grey_Collar_Worker_popularity' : [],
    'Retired_popularity' : [],
    'Self_Employed_popularity' : [],
    'State_Employees_popularity' : [],
    'Student_popularity' : [],
    'Unemployed_popularity' : [],
    'White_Collar_Worker_popularity' : [],
}

indicator_dict_list = {
    'ImmigrationDemand' : [],
    'Globalco2' : [],
    'HighIncome' : [],
    'LowIncome' : [],
    'middleincome' : [],
    'Terrorism' : [],
    'Airtravel' : [],
    'Alcoholconsumption' : [],
    'AverageTemperature' : [],
    'BusinessConfidence' : [],
    'Bususage' : [],
    'ElectricCarTransition' : [],
    'Carusage' : [],
    'Charity' : [],
    'Co2emissions' : [],
    'Corruption' : [],
    'Crimerate' : [],
    'RacialTension' : [],
    'Democracy' : [],
    'Education' : [],
    'Emigration' : [],
    'Energyefficiency' : [],
    'Environment' : [],
    'Equality' : [],
    'FoodPrice' : [],
    'Currencystrength' : [],
    'Foreignaidreceived' : [],
    'Foreigninvestment' : [],
    'Foreignrelations' : [],
    'Gdp' : [],
    'Genderequality' : [],
    'Generationalwealthgap' : [],
    'Health' : [],
    'Tobaccouse' : [],
    'Healthcaredemand' : [],
    'Humandevelopment' : [],
    'Immigration' : [],
    'Illegalimmigration' : [],
    'Industrialautomation' : [],
    'Inflation' : [],
    'Internationaltrade' : [],
    'Internetcurrencyadoption' : [],
    'Internetspeed' : [],
    'Legaldrugconsumption' : [],
    'Lifespan' : [],
    'Oildemand' : [],
    'Oilprice' : [],
    'Oilsupply' : [],
    'Population' : [],
    'Povertyrate' : [],
    'Privateenergy' : [],
    'Privatehealthcare' : [],
    'Privatehousing' : [],
    'Privatepensions' : [],
    'Privaterail' : [],
    'Privateschools' : [],
    'Privatetelecoms' : [],
    'Privatewater' : [],
    'RailUsage' : [],
    'Stability' : [],
    'Technology' : [],
    'Tourism' : [],
    'Trafficcongestion' : [],
    'Unemployment' : [],
    'Veganism' : [],
    'Violentcrimerate' : [],
    'Wages' : [],
    'Workerproductivity' : [],
    'Workingweek' : [],
    'Rareearthprice' : [],
    'Mentalhealth' : []
}

policy_pool = [
(abortionlaw_function, ["Abortionlaw"]), 
(adulteducationsubsidies_function, ["Adulteducationsubsidies"]), 
(agriculturesubsidies_function, ["Agriculturesubsidies"]),
(airlinetax_function, ["Airlinetax"]),
(alcoholawarenesscampaign_function, ["Alcoholawarenesscampaign"]),
(alcohollaw_function, ["Alcohollaw"]),
(alcoholtax_function, ["Alcoholtax"]),
(antibioticsban_function, ["Antibioticsban"]),
(anticorruptionagency_function, ["Anticorruptionagency"]),
(armedpolice_function, ["Armedpolice"]),
(artssubsidies_function, ["Artssubsidies"]),
(automationtax_function, ["Automationtax"]),
(bancoal_function, ["Bancoal"]),
(bandivorce_function, ["Bandivorce"]),
(banforeignchurchservice_function, ["Banforeignchurchservice"]),
(banhomosexuality_function, ["Banhomosexuality"]),
(banlowmpgcars_function, ["Banlowmpgcars"]),
(banprivateeducation_function, ["Banprivateeducation"]),
(banprivatehealthcare_function, ["Banprivatehealthcare"]),
(bansecondhomeownership_function, ["Bansecondhomeownership"]),
(bansundayshopping_function, ["Bansundayshopping"]),
(bicyclesubsidies_function, ["Bicyclesubsidies"]),
(biofuelsubsidies_function, ["Biofuelsubsidies"]),
(bodycameras_function, ["Bodycameras"]),
(bordercontrols_function, ["Bordercontrols"]),
(borderwall_function, ["Borderwall"]),
(businessstartupcampaign_function, ["Businessstartupcampaign"]),
(buslanes_function, ["Buslanes"]),
(bussubsidies_function, ["Bussubsidies"]),
(capceopaymultiplier_function, ["Capceopaymultiplier"]),
(capitalcontrols_function, ["Capitalcontrols"]),
(capitalgainstax_function, ["Capitalgainstax"]),
(carboncaptureandstorage_function, ["Carboncaptureandstorage"]),
(carbontax_function, ["Carbontax"]),
(caremmissionslimits_function, ["Caremmissionslimits"]),
(carpoolingcampaign_function, ["Carpoolingcampaign"]),
(cartax_function, ["Cartax"]),
(cctvcameras_function, ["Cctvcameras"]),
(charitytaxrelief_function, ["Charitytaxrelief"]),
(childbenefit_function, ["Childbenefit"]),
(childcareprovision_function, ["Childcareprovision"]),
(citizenshiptests_function, ["Citizenshiptests"]),
(cityfarms_function, ["Cityfarms"]),
(cleanenergysubsidies_function, ["Cleanenergysubsidies"]),
(cleanfuelsubsidy_function, ["Cleanfuelsubsidy"]),
(climatechangeadaptionfund_function, ["Climatechangeadaptionfund"]),
(closeairportscompletely_function, ["Closeairportscompletely"]),
(communitypolicing_function, ["Communitypolicing"]),
(compulsorychurchattendance_function, ["Compulsorychurchattendance"]),
(compulsoryfoodlabelling_function, ["Compulsoryfoodlabelling"]),
(compulsoryforeignlanguageclasses_function, ["Compulsoryforeignlanguageclasses"]),
(compulsorylanguagelessons_function, ["Compulsorylanguagelessons"]),
(compulsoryschoolsports_function, ["Compulsoryschoolsports"]),
(compulsoryworkfortheunemployed_function, ["Compulsoryworkfortheunemployed"]),
(congestioncharging_function, ["Congestioncharging"]),
(consumerrights_function, ["Consumerrights"]),
(corporationtax_function, ["Corporationtax"]),
(creationism_function, ["Creationism"]),
(curfews_function, ["Curfews"]),
(cyberbullyingawarenesscampaign_function, ["Cyberbullyingawarenesscampaign"]),
(cyclingcampaign_function, ["Cyclingcampaign"]),
(deathpenalty_function, ["Deathpenalty"]),
(detentionwithouttrial_function, ["Detentionwithouttrial"]),
(diplomaticservice_function, ["Diplomaticservice"]),
(disabilitybenefit_function, ["Disabilitybenefit"]),
(diversityquotasforcompanies_function, ["Diversityquotasforcompanies"]),
(divertedprofitstax_function, ["Divertedprofitstax"]),
(driverlesscarlaws_function, ["Driverlesscarlaws"]),
(dronestrikeact_function, ["Dronestrikeact"]),
(drugenforcement_function, ["Drugenforcement"]),
(drugtreatment_function, ["Drugtreatment"]),
(ecohomeregulations_function, ["Ecohomeregulations"]),
(electriccarsinitiative_function, ["Electriccarsinitiative"]),
(emptyhomestax_function, ["Emptyhomestax"]),
(enterpriseinvestmentscheme_function, ["Enterpriseinvestmentscheme"]),
(executivetermlength_function, ["Executivetermlength"]),
(executivetermlimit_function, ["Executivetermlimit"]),
(faithschoolsubsidies_function, ["Faithschoolsubsidies"]),
(familyplanning_function, ["Familyplanning"]),
(femalegenitalmutilationban_function, ["Femalegenitalmutilationban"]),
(financialtransactionstax_function, ["Financialtransactionstax"]),
(flagsoneverystreetcorner_function, ["Flagsoneverystreetcorner"]),
(flattax_function, ["Flattax"]),
(foodstamps_function, ["Foodstamps"]),
(foodstandards_function, ["Foodstandards"]),
(foreignaid_function, ["Foreignaid"]),
(foreigninvestmentrestrictions_function, ["Foreigninvestmentrestrictions"]),
(foreigninvestortaxbreaks_function, ["Foreigninvestortaxbreaks"]),
(freebuspasses_function, ["Freebuspasses"]),
(freeeyetests_function, ["Freeeyetests"]),
(freeparentingclasses_function, ["Freeparentingclasses"]),
(freeschoolmeals_function, ["Freeschoolmeals"]),
(frequentflyertax_function, ["Frequentflyertax"]),
(fuelefficiency_function, ["Fuelefficiency"]),
(gambling_function, ["Gambling"]),
(gamehunting_function, ["Gamehunting"]),
(gatedcommunities_function, ["Gatedcommunities"]),
(gaymarriage_function, ["Gaymarriage"]),
(genderdiscriminationact_function, ["Genderdiscriminationact"]),
(gendertransition_function, ["Gendertransition"]),
(generalmediacensorship_function, ["Generalmediacensorship"]),
(governmentsubsidiesforunions_function, ["Governmentsubsidiesforunions"]),
(graduatetax_function, ["Graduatetax"]),
(greenelectronicsinitiative_function, ["Greenelectronicsinitiative"]),
(handgunlaws_function, ["Handgunlaws"]),
(healthcarevouchers_function, ["Healthcarevouchers"]),
(healthfoodsubsidies_function, ["Healthfoodsubsidies"]),
(healthtaxcredits_function, ["Healthtaxcredits"]),
(healthyeatingcampaign_function, ["Healthyeatingcampaign"]),
(helicoptermoney_function, ["Helicoptermoney"]),
(humancloningresearchgrants_function, ["Humancloningresearchgrants"]),
(hybridcarsinitiative_function, ["Hybridcarsinitiative"]),
(idcards_function, ["Idcards"]),
(importtarrifs_function, ["Importtarrifs"]),
(incometax_function, ["Incometax"]),
(inheritancetax_function, ["Inheritancetax"]),
(intellectualpropertyrights_function, ["Intellectualpropertyrights"]),
(intelligenceservices_function, ["Intelligenceservices"]),
(internationalfusionresearchproject_function, ["Internationalfusionresearchproject"]),
(internetcensorship_function, ["Internetcensorship"]),
(internetcurrencytaxation_function, ["Internetcurrencytaxation"]),
(internettax_function, ["Internettax"]),
(judiciaryindependence_function, ["Judiciaryindependence"]),
(junkfoodtax_function, ["Junkfoodtax"]),
(jurytrial_function, ["Jurytrial"]),
(keepthecountrytidycampaign_function, ["Keepthecountrytidycampaign"]),
(labordaybankholiday_function, ["Labordaybankholiday"]),
(labourlaws_function, ["Labourlaws"]),
(legalaid_function, ["Legalaid"]),
(legaliseprostitution_function, ["Legaliseprostitution"]),
(limitautomatedtrading_function, ["Limitautomatedtrading"]),
(limitorbancarsincities_function, ["Limitorbancarsincities"]),
(luxurygoodstax_function, ["Luxurygoodstax"]),
(mandatorymicrochipimplant_function, ["Mandatorymicrochipimplant"]),
(mandatorymicrogeneration_function, ["Mandatorymicrogeneration"]),
(mansiontax_function, ["Mansiontax"]),
(marriedtaxallowance_function, ["Marriedtaxallowance"]),
(marsprogram_function, ["Marsprogram"]),
(maternityleave_function, ["Maternityleave"]),
(microgenerationgrants_function, ["Microgenerationgrants"]),
(militaryspending_function, ["Militaryspending"]),
(minimumwage_function, ["Minimumwage"]),
(monorail_function, ["Monorail"]),
(mortgagetaxrelief_function, ["Mortgagetaxrelief"]),
(narcotics_function, ["Narcotics"]),
(nationalanthematstartofnews_function, ["Nationalanthematstartofnews"]),
(nationalanthemsinschool_function, ["Nationalanthemsinschool"]),
(nationalarmedforcesweek_function, ["Nationalarmedforcesweek"]),
(nationalbusinesscouncil_function, ["Nationalbusinesscouncil"]),
(nationalservice_function, ["Nationalservice"]),
(needleexchangeprogram_function, ["Needleexchangeprogram"]),
(newcarsubsidies_function, ["Newcarsubsidies"]),
(nuclearfission_function, ["Nuclearfission"]),
(oildrillingsubsidy_function, ["Oildrillingsubsidy"]),
(onechildpolicy_function, ["Onechildpolicy"]),
(organdonation_function, ["Organdonation"]),
(organicsubsidy_function, ["Organicsubsidy"]),
(payrolltax_function, ["Payrolltax"]),
(petroltax_function, ["Petroltax"]),
(phonetapping_function, ["Phonetapping"]),
(plasticbagtax_function, ["Plasticbagtax"]),
(policedrones_function, ["Policedrones"]),
(pollutioncontrols_function, ["Pollutioncontrols"]),
(pressfreedom_function, ["Pressfreedom"]),
(prisonertagging_function, ["Prisonertagging"]),
(prisonervoting_function, ["Prisonervoting"]),
(privateprisons_function, ["Privateprisons"]),
(propertytax_function, ["Propertytax"]),
(proportionalfines_function, ["Proportionalfines"]),
(publiclibraries_function, ["Publiclibraries"]),
(publicreligiousbroadcasts_function, ["Publicreligiousbroadcasts"]),
(publictaxreturns_function, ["Publictaxreturns"]),
(punitivetaxonsuperstores_function, ["Punitivetaxonsuperstores"]),
(punitivewealthtax_function, ["Punitivewealthtax"]),
(quantitativeeasing_function, ["Quantitativeeasing"]),
(racediscriminationact_function, ["Racediscriminationact"]),
(racialprofiling_function, ["Racialprofiling"]),
(rareearthrefinement_function, ["Rareearthrefinement"]),
(recreationaldrugstax_function, ["Recreationaldrugstax"]),
(recycling_function, ["Recycling"]),
(reforestation_function, ["Reforestation"]),
(rentcontrols_function, ["Rentcontrols"]),
(retirementage_function, ["Retirementage"]),
(righttodie_function, ["Righttodie"]),
(righttoprivacy_function, ["Righttoprivacy"]),
(roadbuilding_function, ["Roadbuilding"]),
(roboticsresearch_function, ["Roboticsresearch"]),
(rubberbullets_function, ["Rubberbullets"]),
(ruraldevelopmentgrants_function, ["Ruraldevelopmentgrants"]),
(salestax_function, ["Salestax"]),
(sateliteroadpricing_function, ["Sateliteroadpricing"]),
(schoolbuses_function, ["Schoolbuses"]),
(schoolprayers_function, ["Schoolprayers"]),
(schooltaxcredits_function, ["Schooltaxcredits"]),
(schoolvouchers_function, ["Schoolvouchers"]),
(sciencefunding_function, ["Sciencefunding"]),
(secretcourts_function, ["Secretcourts"]),
(selectiveschooling_function, ["Selectiveschooling"]),
(smallbusinessgrants_function, ["Smallbusinessgrants"]),
(smartmeterprogram_function, ["Smartmeterprogram"]),
(socialcare_function, ["Socialcare"]),
(socialjusticefoundation_function, ["Socialjusticefoundation"]),
(spaceprogram_function, ["Spaceprogram"]),
(statebroadcaster_function, ["Statebroadcaster"]),
(statehealthservice_function, ["Statehealthservice"]),
(stateschools_function, ["Stateschools"]),
(stemcells_function, ["Stemcells"]),
(syntheticmeatresearchgrants_function, ["Syntheticmeatresearchgrants"]),
(universalbasicincome_function, ["Universalbasicincome"]),
(refugeepolicy_function, ["Refugeepolicy"]),
(statereligion_function, ["Statereligion"]),
(desalination_function, ["Desalination"]),
(immigrationrules_function, ["Immigrationrules"]),
(nuclearweapons_function, ["Nuclearweapons"]),
(co2campaign_function, ["Co2campaign"]),
(banalcohol_function, ["Banalcohol"]),
(bantobacco_function, ["Bantobacco"]),
(bancrypto_function, ["Bancrypto"]),
(workersdividend_function, ["Workersdividend"])
]

#Call function
def safe_call(func, args_keys):
    # Fetch values from policy_callout using the keys provided in args_keys
    args = [pcd.get(key) for key in args_keys]  # This fetches values using the keys from the dictionary

    # Check if all arguments are not None
    if all(arg is not None for arg in args):
        return func(*args)  # Call the function with the arguments
    else:
        print(f"Skipped {func.__name__} due to None values in arguments")

def traning_data_generation():
    round_num = 1000
    counter = 0

    for r in range(round_num):
        counter += 1
        #Call
        for func, args_keys in policy_pool:
            safe_call(func, args_keys)


        if r > 0:
            update_random()

        # Function parameter data record
        for i in policy_callout_dict:
            for key, value in pcd.items():
                if key == i:
                    policy_callout_dict[i].append(value)

        # Popularity data record
        popularity_dict = {
        "Capitalism_popularity": round(popularity.Capitalism_popularity, 2),
        "Isolationism_popularity": round(popularity.Isolationism_popularity, 2),
        "Nationalism_popularity": round(popularity.Nationalism_popularity, 2),
        "Centrism_popularity": round(popularity.Centrism_popularity, 2),
        "Liberalism_popularity": round(popularity.Liberalism_popularity, 2),
        "Internationalism_popularity": round(popularity.Internationalism_popularity, 2),
        "Male_Supremacy_Advocates_popularity": round(popularity.Male_Supremacy_Advocates_popularity, 2),
        "Traditional_Law_and_Order_advocates_popularity": round(popularity.Traditional_Law_and_Order_advocates_popularity, 2),
        "Feminism_popularity": round(popularity.Feminism_popularity, 2),
        "Communism_popularity": round(popularity.Communism_popularity, 2),
        "Socialism_popularity": round(popularity.Socialism_popularity, 2),
        "Democratic_Socialism_popularity": round(popularity.Democratic_Socialism_popularity, 2),
        "Social_Democracy_popularity": round(popularity.Social_Democracy_popularity, 2),
        "Progressive_popularity": round(popularity.Progressive_popularity, 2),
        "Secularism_popularity": round(popularity.Secularism_popularity, 2),
        "Fiscal_Conservatism_popularity": round(popularity.Fiscal_Conservatism_popularity, 2),
        "Conservatism_popularity": round(popularity.Conservatism_popularity, 2),
        "Libertarian_Capitalism_popularity": round(popularity.Libertarian_Capitalism_popularity, 2),
        "Neoliberalism_popularity": round(popularity.Neoliberalism_popularity, 2),
        "Laissez_faire_Capitalism_popularity": round(popularity.Laissez_faire_Capitalism_popularity, 2),
        "Totalitarianism_popularity": round(popularity.Totalitarianism_popularity, 2),
        "Elitism_popularity": round(popularity.Elitism_popularity, 2),
        "Religious_Fundamentalism_popularity": round(popularity.Religious_Fundamentalism_popularity, 2),
        "Progressivism_popularity": round(popularity.Progressivism_popularity, 2),
        "Libertarianism_popularity": round(popularity.Libertarianism_popularity, 2),
        "Anarchism_popularity": round(popularity.Anarchism_popularity, 2),
        "Environmentalism_popularity": round(popularity.Environmentalism_popularity, 2),
        "Technological_Optimism_popularity": round(popularity.Technological_Optimism_popularity, 2),
        "Industrialism_popularity": round(popularity.Industrialism_popularity, 2),
        "Altruism_popularity": round(popularity.Altruism_popularity, 2),
        "Collectivism_popularity": round(popularity.Collectivism_popularity, 2),
        "Individualism_popularity": round(popularity.Individualism_popularity, 2),
        "Egoism_popularity": round(popularity.Egoism_popularity, 2),
        "Populism_popularity": round(popularity.Populism_popularity, 2),
        "Free_Trade_Advocates_popularity": round(popularity.Free_Trade_Advocates_popularity, 2),
        "Protectionism_popularity": round(popularity.Protectionism_popularity, 2),
        "Economic_Nationalism_popularity": round(popularity.Economic_Nationalism_popularity, 2),
        "Postmodernism_popularity": round(popularity.Postmodernism_popularity, 2),
        "Modernism_popularity": round(popularity.Modernism_popularity, 2),
        "Scientific_Progressivism_popularity": round(popularity.Scientific_Progressivism_popularity, 2),
        "Cultural_Traditionalism_popularity": round(popularity.Cultural_Traditionalism_popularity, 2),
        "Traditionalism_popularity": round(popularity.Traditionalism_popularity, 2),
        "Globalization_supporters_popularity": round(popularity.Globalization_supporters_popularity, 2),
        "International_Cooperation_Advocates_popularity": round(popularity.International_Cooperation_Advocates_popularity, 2),
        "Patriotic_movements_popularity": round(popularity.Patriotic_movements_popularity, 2),
        "National_Security_Advocates_popularity": round(popularity.National_Security_Advocates_popularity, 2),
        "Patriotic_Education_Advocates_popularity": round(popularity.Patriotic_Education_Advocates_popularity, 2),
        "AntiCorruption_movements_popularity": round(popularity.AntiCorruption_movements_popularity, 2),
        "Labor_Movements_popularity": round(popularity.Labor_Movements_popularity, 2),
        "Social_Welfare_Advocates_popularity": round(popularity.Social_Welfare_Advocates_popularity, 2),
        "Educational_Equity_Advocates_popularity": round(popularity.Educational_Equity_Advocates_popularity, 2),
        "Universal_Healthcare_Advocates_popularity": round(popularity.Universal_Healthcare_Advocates_popularity, 2),
        "Market_Reform_Advocates_popularity": round(popularity.Market_Reform_Advocates_popularity, 2),
        "Tax_Reform_advocates_popularity": round(popularity.Tax_Reform_advocates_popularity, 2),
        "Redistribution_Advocates_popularity": round(popularity.Redistribution_Advocates_popularity, 2),
        "Economic_Equality_Advocates_popularity": round(popularity.Economic_Equality_Advocates_popularity, 2),
        "Housing_Equity_Advocates_popularity": round(popularity.Housing_Equity_Advocates_popularity, 2),
        "Economic_Stimulus_Advocates_popularity": round(popularity.Economic_Stimulus_Advocates_popularity, 2),
        "Global_Climate_Advocates_popularity": round(popularity.Global_Climate_Change_Advocates_popularity, 2),
        "Animal_Rights_Advocates_popularity": round(popularity.Animal_Rights_Advocates_popularity, 2),
        "Climate_Advocates_popularity": round(popularity.Climate_Change_Advocates_popularity, 2),
        "Sustainable_Agriculture_Advocates_popularity": round(popularity.Sustainable_Agriculture_Advocates_popularity, 2),
        "Human_Rights_movements_popularity": round(popularity.Human_Rights_movements_popularity, 2),
        "Democracy_advocates_popularity": round(popularity.Democracy_advocates_popularity, 2),
        "Civil_Liberties_Advocates_popularity": round(popularity.Civil_Liberties_Advocates_popularity, 2),
        "Social_Justice_Advocates_popularity": round(popularity.Social_Justice_Advocates_popularity, 2),
        "Social_Equality_Advocates_popularity": round(popularity.Social_Equality_Advocates_popularity, 2),
        "Individual_Rights_Advocates_popularity": round(popularity.Individual_Rights_Advocates_popularity, 2),
        "Privacy_advocates_popularity": round(popularity.Privacy_advocates_popularity, 2),
        "Open_Source_Advocates_popularity": round(popularity.Open_Source_Advocates_popularity, 2),
        "Cryptocurrency_Advocates_popularity": round(popularity.Cryptocurrency_Advocates_popularity, 2),
        "Digital_Freedom_Advocates_popularity": round(popularity.Digital_Freedom_Advocates_popularity, 2),
        "Digital_Economy_Advocates_popularity": round(popularity.Digital_Economy_Advocates_popularity, 2),
        "Free_Internet_Advocates_popularity": round(popularity.Free_Internet_Advocates_popularity, 2),
        "Community_movements_popularity": round(popularity.Community_movements_popularity, 2),
        "Peace_movements_popularity": round(popularity.Peace_movements_popularity, 2),
        "Consumer_Rights_advocates_popularity": round(popularity.Consumer_Rights_advocates_popularity, 2),
        "Science_education_advocates_popularity": round(popularity.Science_education_advocates_popularity, 2),
        "Free_Market_Advocates_popularity": round(popularity.Free_Market_Advocates_popularity, 2),
        "Regulation_Advocates_popularity": round(popularity.Regulation_Advocates_popularity, 2),
        "Gun_Rights_Advocates_popularity": round(popularity.Gun_Rights_Advocates_popularity, 2),
        "Drug_Reform_Advocates_popularity": round(popularity.Drug_Reform_Advocates_popularity, 2),
        "Law_and_Order_Advocates_popularity": round(popularity.Law_and_Order_Advocates_popularity, 2),
        "Anti_Militarism_Advocates_popularity": round(popularity.Anti_Militarism_Advocates_popularity, 2),
        "Harm_Reduction_Advocates_popularity": round(popularity.Harm_Reduction_Advocates_popularity, 2),
        "Hardline_Drug_Policy_Advocates_popularity": round(popularity.Hardline_Drug_Policy_Advocates_popularity, 2),
        "Anti_Nuclear_Advocates_popularity": round(popularity.Anti_Nuclear_Advocates_popularity, 2),
        "Medical_Ethics_Advocates_popularity": round(popularity.Medical_Ethics_Advocates_popularity, 2),
        "Health_movements_popularity": round(popularity.Health_movements_popularity, 2),
        "Housing_rights_activists_popularity": round(popularity.Housing_rights_activists_popularity, 2),
        "Public_Transport_Advocates_popularity": round(popularity.Public_Transport_Advocates_popularity, 2),
        "Homeownership_Advocates_popularity": round(popularity.Homeownership_Advocates_popularity, 2),
        "Religious_popularity": round(popularity.Religious_popularity, 2),
        "Young_popularity": round(popularity.Young_popularity, 2),
        "Patriot_popularity": round(popularity.Patriot_popularity, 2),
        "Parents_popularity": round(popularity.Parents_popularity, 2),
        "Middle_Class_popularity": round(popularity.Middle_Class_popularity, 2),
        "Poor_popularity": round(popularity.Poor_popularity, 2),
        "Wealthy_popularity": round(popularity.Wealthy_popularity, 2),
        "Commuter_popularity": round(popularity.Commuter_popularity, 2),
        "Motorist_popularity": round(popularity.Motorist_popularity, 2),
        "Academic_popularity": round(popularity.Academic_popularity, 2),
        "Blue_Collar_Worker_popularity": round(popularity.Blue_Collar_Worker_popularity, 2),
        "Farmers_popularity": round(popularity.Farmers_popularity, 2),
        "Grey_Collar_Worker_popularity": round(popularity.Grey_Collar_Worker_popularity, 2),
        "Retired_popularity": round(popularity.Retired_popularity, 2),
        "Self_Employed_popularity": round(popularity.Self_Employed_popularity, 2),
        "State_Employees_popularity": round(popularity.State_Employees_popularity, 2),
        "Student_popularity": round(popularity.Student_popularity, 2),
        "Unemployed_popularity": round(popularity.Unemployed_popularity, 2),
        "White_Collar_Worker_popularity": round(popularity.White_Collar_Worker_popularity, 2)
        }
        
        for key, value in popularity_dict.items():
            for p in popularity_dict_list:
                if key == p:
                    popularity_dict_list[p].append(value)

        if i == 1:
            for key, value in popularity_dict.items():
                if str(value) == "[]":
                    popularity_dict_list[key] = 0

        # Indicator data record
        indicator_dict = {
            'ImmigrationDemand': round(simulation_callout.ImmigrationDemand,2),
            'Globalco2': round(simulation_callout.GlobalCO2,2),
            'HighIncome': round(simulation_callout.HighIncome,2),
            'LowIncome': round(simulation_callout.LowIncome,2),
            'middleincome': round(simulation_callout.middleincome,2),
            'Terrorism': round(simulation_callout.Terrorism,2),
            'Airtravel': round(simulation_callout.airtravel,2),
            'Alcoholconsumption': round(simulation_callout.alcoholconsumption,2),
            'AverageTemperature': round(simulation_callout.AverageTemperature,2),
            'BusinessConfidence': round(simulation_callout.BusinessConfidence,2),
            'Bususage': round(simulation_callout.bususage,2),
            'ElectricCarTransition': round(simulation_callout.ElectricCarTransition,2),
            'Carusage': round(simulation_callout.carusage,2),
            'Charity': round(simulation_callout.charity,2),
            'Co2emissions': round(simulation_callout.co2emissions,2),
            'Corruption': round(simulation_callout.corruption,2),
            'Crimerate': round(simulation_callout.crimerate,2),
            'RacialTension': round(simulation_callout.RacialTension,2),
            'Democracy': round(simulation_callout.democracy,2),
            'Education': round(simulation_callout.education,2),
            'Emigration': round(simulation_callout.emigration,2),
            'Energyefficiency': round(simulation_callout.energyefficiency,2),
            'Environment': round(simulation_callout.environment,2),
            'Equality': round(simulation_callout.Equality,2),
            'FoodPrice': round(simulation_callout.FoodPrice,2),
            'Currencystrength': round(simulation_callout.currencystrength,2),
            'Foreignaidreceived': round(simulation_callout.foreignaidreceived,2),
            'Foreigninvestment': round(simulation_callout.foreigninvestment,2),
            'Foreignrelations': round(simulation_callout.foreignrelations,2),
            'Gdp': round(simulation_callout.gdp,2),
            'Genderequality': round(simulation_callout.genderequality,2),
            'Generationalwealthgap': round(simulation_callout.generationalwealthgap,2),
            'Health': round(simulation_callout.health,2),
            'Tobaccouse': round(simulation_callout.tobaccouse,2),
            'Healthcaredemand': round(simulation_callout.healthcaredemand,2),
            'Humandevelopment': round(simulation_callout.humandevelopment,2),
            'Immigration': round(simulation_callout.immigration,2),
            'Illegalimmigration': round(simulation_callout.illegalimmigration,2),
            'Industrialautomation': round(simulation_callout.industrialautomation,2),
            'Inflation': round(simulation_callout.Inflation,2),
            'Internationaltrade': round(simulation_callout.internationaltrade,2),
            'Internetcurrencyadoption': round(simulation_callout.internetcurrencyadoption,2),
            'Internetspeed': round(simulation_callout.internetspeed,2),
            'Legaldrugconsumption': round(simulation_callout.legaldrugconsumption,2),
            'Lifespan': round(simulation_callout.lifespan,2),
            'Oildemand': round(simulation_callout.oildemand,2),
            'Oilprice': round(simulation_callout.oilprice,2),
            'Oilsupply': round(simulation_callout.oilsupply,2),
            'Population': round(simulation_callout.population,2),
            'Povertyrate': round(simulation_callout.povertyrate,2),
            'Privateenergy': round(simulation_callout.privateenergy,2),
            'Privatehealthcare': round(simulation_callout.privatehealthcare,2),
            'Privatehousing': round(simulation_callout.privatehousing,2),
            'Privatepensions': round(simulation_callout.privatepensions,2),
            'Privaterail': round(simulation_callout.privaterail,2),
            'Privateschools': round(simulation_callout.privateschools,2),
            'Privatetelecoms': round(simulation_callout.privatetelecoms,2),
            'Privatewater': round(simulation_callout.privatewater,2),
            'RailUsage': round(simulation_callout.railUsage,2),
            'Stability': round(simulation_callout.stability,2),
            'Technology': round(simulation_callout.technology,2),
            'Tourism': round(simulation_callout.Tourism,2),
            'Trafficcongestion': round(simulation_callout.trafficcongestion,2),
            'Unemployment': round(simulation_callout.unemployment,2),
            'Veganism': round(simulation_callout.veganism,2),
            'Violentcrimerate': round(simulation_callout.violentcrimerate,2),
            'Wages': round(simulation_callout.wages,2),
            'Workerproductivity': round(simulation_callout.workerproductivity,2),
            'Workingweek': round(simulation_callout.workingweek,2),
            'Rareearthprice': round(simulation_callout.rareearthprice,2),
            'Mentalhealth': round(simulation_callout.mentalhealth,2),
        }

        for key, value in indicator_dict.items():
            for p in indicator_dict_list:
                if key == p:
                    indicator_dict_list[p].append(value)

        if i == 1:
            for key, value in indicator_dict.items():
                if str(value) == "[]":
                    indicator_dict_list[key] = 0

        print("Creating traning data:"+str(counter), end = "\r")

    data = policy_callout_dict | popularity_dict_list | indicator_dict_list 

    #Get max length of any element in this list

    max_length = max(len(lst) for lst in data.values())

    for key, value in data.items():
        if not value:  # Check if the list is empty
            data[key] = [0] * max_length  # Fill with zeros


    file_path = r'final_year_project\config\training_data.json'
    with open(file_path, 'w') as file:
        json.dump(data, file, indent=4)  # Using indent for pretty printing



